### PR TITLE
Few features: Weather Item

### PR DESCRIPTION
**Pull request by yusufozgul**
**Features Added:**
- Weather Item: It determines the weather of your location every 30 minutes.

**Fixes**
- Change defaults to Defaults: -> Defaults Framework v3.0.0 update changes

**Tested?**
- Try get weather and show Touch Bar 

**Test Configuration:**
- Hardware: MacBook Pro 2016
- macOS Version: 10.15 Beta
- Xcode version: 11.0

**Checklist**
Use this list to keep track of your progress:

- [ X ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ X ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

Notes:
Weather source weather.com.
Location permission is required for the weather to work.
The weather is refreshed every 30 minutes.
Data is retrieved using Alamofire.

### CODE REVIEW

**Comment by unnamedd** [comment]
I have a question: I was reading your PR and I saw you added a Alamofire in the project just to request for one endpoint, then I wonder: why not use URLSession? 

Here is one example: https://github.com/pigigaldi/Pock/blob/1c7506e49eb5585b4e9129b90c5a8c0b55eb57c1/Pock/Preferences/Panes/GeneralPreferencePane/GeneralPreferencePane.swift#L134

**Comment by yusufozgul** [comment]
@unnamedd hi, while I was working on it, I used Alamofire to make it easier to add other features. I can use URLSession if you want.

**Comment by unnamedd** [comment]
IMO you should use for two reasons: first because no one will have to install one more dependency to do a simple request and second, you will learn and understand how to use URLSession which is quite simple and already have precedence of use throughout the project!

If you want, I can do a complete review in your PR.

**Comment by pigigaldi** [comment]
Sorry guys, but based on this shot, I have a different plan for this ”weather feature.”
https://www.instagram.com/p/Bx6yG01I6oB/?igshid=gnyaod8oww58

I hope to finish full PockKit integration soon, so you'll be able to create your widgets easily and without hard-coding them inside Pock.

**Comment by yusufozgul** [comment]
Your design is much more beautiful.  See you at another PR in the future.

**Comment by microvnhaxor** [comment]
Is there any updates for this work guys?

**Comment by yusufozgul** [comment]
> Is there any updates for this work guys?

I'm not working, but @pigigaldi may be.

**Comment by microvnhaxor** [comment]
@yusufozgul , can you share your project ( contains weather ) to me ?

**Comment by yusufozgul** [comment]
> @yusufozgul , can you share your project ( contains weather ) to me ?

Oh no, sorry i deleted weather module. I can help you if you want to developing

**Comment by microvnhaxor** [comment]
Thank you brother, I was able to rebuild it.

**Pull request closed without merging**
