### PR TITLE
add a few buttons

### LINKED ISSUE #273: Time Format TextField Changes to Default When Pock Restarts
**Describe the bug**
Time format textfield changes to default everytime pock restarts.
The touch bar stays fine , but the time format text changes

**How to reproduce**
restart Pock

**Expected behavior**
time format text stays what I setted

**Screenshots**
demo

**Versions:**
 - macOS version: [10.15.1]
 - Pock version:  [0.6.3]

### PR DESCRIPTION
**Pull request by L1cardo**
---
name: Pull request
about: Create a pull request to contribute in making Pock amazing!
title: add single volume toggle and single brightness toggle button
labels: add single volume toggle and single brightness toggle button
assignees: ''

---

**Describe the Pull request**
1. add single volume toggle and single brightness toggle button.
2. volume toggle button's icon can changes depends on current system volume.
3. add screensaver button #256 
4. fix #273 

**Screenshots**

demo

**Pull request type**

- [x] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

**Tested?**
Yes

*Test Configuration*:
* Hardware:      [MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)]
* macOS Version: [10.15.1]
* Xcode version: [11.2]

**Checklist**
Use this list to keep track of your progress:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by L1cardo** [comment]
demo

**Comment by L1cardo** [comment]
add system-like mute icon

unmuted：
image


muted：
image

**Comment by L1cardo** [comment]
add high resolution icons

before：
image

after：
image

**Comment by L1cardo** [comment]
add screensaver button

[Demo Here](https://youtu.be/rxO8aHXDg6M)

**Comment by L1cardo** [comment]
@pigigaldi
When system is muted, `NSSound.isMuted` returns `false. `When the system is unmuted, it returns `true`.
I think it returns last value and is not writable.
I don’t know how to detect if the system is muted or unmuted, so that I don’t know which icon the volume button should display.
Do you have any idea?

**Comment by andreashanft** [comment]
@L1cardo I think your pull request is a great addition and I would like to help. If I understand you correctly, you have no reliable way of how to figure out if the system is muted or not?

You could use this code snippet that uses CoreAudio to achieve this: 

```
import CoreAudio

    var isAudioMuted: Bool {
         var defaultHardwareAddress = AudioObjectPropertyAddress(
            mSelector: AudioObjectPropertySelector(kAudioHardwarePropertyDefaultOutputDevice),
            mScope: AudioObjectPropertyScope(kAudioObjectPropertyScopeGlobal),
            mElement: AudioObjectPropertyElement(kAudioObjectPropertyElementMaster))

         var defaultAudioHardwareID: AudioDeviceID = 0
         var defaultHardwarePropertySize = UInt32(MemoryLayout<uint32>.size)
        
        _ = AudioObjectGetPropertyData(
            AudioObjectID(kAudioObjectSystemObject),
            &defaultHardwareAddress, 0 , nil,
            &defaultHardwarePropertySize,
            &defaultAudioHardwareID)
        
         // kAudioDevicePropertyMute: A UInt32 where a value of 1 means that mute is enabled making that element inaudible.
         var muteStatusAddress = AudioObjectPropertyAddress(
            mSelector: AudioObjectPropertySelector(kAudioDevicePropertyMute),
            mScope: AudioObjectPropertyScope(kAudioObjectPropertyScopeOutput),
            mElement: AudioObjectPropertyElement(kAudioObjectPropertyElementMaster))
        
        var isMuted: uint32 = 0
        var muteStatusPropertySize = UInt32(MemoryLayout<uint32>.size)

         _ = AudioObjectGetPropertyData(
            defaultAudioHardwareID,
            &muteStatusAddress, 0, nil,
            &muteStatusPropertySize,
            &isMuted)

         print("Mute Status: \((isMuted == 1) ? "muted" : "unmuted")")
        
        return isMuted == 1
    }
```

**Comment by L1cardo** [comment]
@andreashanft Hi! Thanks for your help, I will give it a shot this weekend. But now I should  probably working on my exam 😭

**Comment by L1cardo** [comment]
@andreashanft I tested the code that you offer, but it was still the same problem. What I mean is that , `NSSound.isMuted` does not response immediately , it always returns last status of `isMutued`, which is when system is muted, `NSSound.isMuted` returns `false` and when system is unmuted, it returns `true`. So the mute image that is on the touchbar is based on the last status of the `isMutued`, and always not correct .

**Comment by L1cardo** [comment]
change screensaver button icon to the system-like icon
image

**Comment by L1cardo** [comment]
change lock screen icon to the system-like icon

**Comment by L1cardo** [comment]
> @pigigaldi
> When system is muted, `NSSound.isMuted` returns `false. `When the system is unmuted, it returns `true`.
> I think it returns last value and is not writable.
> I don’t know how to detect if the system is muted or unmuted, so that I don’t know which icon the volume button should display.
> Do you have any idea?

I think I have fixed it

**Comment by L1cardo** [comment]
icons of volume mute item and volume toggle item now sync with system volume settings

**Comment by L1cardo** [comment]
add "Do not Disturb" button

You can check it out [here](https://youtu.be/pjCW1hJZCEI)

**Comment by L1cardo** [comment]
add missing localizations
But I have a question:
    Can we have system folders names localized that are shown on Dock ?

触控栏快照2019-12-09下午6 09 27

**Pull request merged**
